### ISSUE TITLE
Error "dkms autoinstall" nvidia jetson

### ISSUE THREAD

**Issue by MargheLofru** [lwfinger/rtl8723bu#199]
I am trying to install the drivers on nvidia jetson nano (uname -r: 4.9.337-tegra), but running the last command "sudo dkms autoinstall $PACKAGE_NAME/$PACKAGE_VERSION", I got the following error
`Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=4.9.337-tegra -C /lib/modules/4.9.337-tegra/build M=/var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build..................(bad exit status: 2)
ERROR (dkms apport): binary package for rtl8723bu: 4.3.6.11_12942.20141204_BTCOEX20140507-4E40 not found
Error! Bad return status for module build on kernel: 4.9.337-tegra (aarch64)
Consult /var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build/make.log for more information.
`

Looking at the make.log file, the problem seems a type variable declaration. How can I solve this issue?
`  CC [M]  /var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build/os_dep/os_intfs.o
  CC [M]  /var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build/os_dep/usb_intf.o
  CC [M]  /var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build/os_dep/usb_ops_linux.o
  CC [M]  /var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build/os_dep/ioctl_linux.o
/var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build/os_dep/usb_intf.c:1414:1: warning: data defini$
 MODULE_IMPORT_NS(VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver);
 ^~~~~~~~~~~~~~~~
/var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build/os_dep/usb_intf.c:1414:1: error: type defaults$
/var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build/os_dep/usb_intf.c:1414:1: warning: parameter n$
  CC [M]  /var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build/os_dep/xmit_linux.o
cc1: some warnings being treated as errors
scripts/Makefile.build:338: recipe for target '/var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build$
make[1]: *** [/var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build/os_dep/usb_intf.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:1656: recipe for target '_module_/var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build' fai$
make: *** [_module_/var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.9.337-tegra-ubuntu18.04_aarch64/kernel-4.9'
`

Thanks a lot!
