### ISSUE TITLE
Errors in make with 5.11 kernel

### ISSUE THREAD

**Issue by kevin201** [lwfinger/rtl8723bu#179]
I'm trying to solve a problem with the device not being recognised after the kernel upgrade to 5.11.0-25

dkms has been working perfectly on every previous kernel upgrade. (5.4, 5,8)

dkms status
rtl8723bu, 4.3.6.11_12942.20141204_BTCOEX20140507-4E40, 5.4.0-80-generic, x86_64: installed
rtl8723bu, 4.3.6.11_12942.20141204_BTCOEX20140507-4E40, 5.8.0-63-generic, x86_64: installed

Problem occurs here:
```
sudo dkms autoinstall $PACKAGE_NAME/$PACKAGE_VERSION

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.11.0-25-generic -C /lib/modules/5.11.0-25-generic/build M=/var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build........(bad exit status: 2)
ERROR (dkms apport): binary package for rtl8723bu: 4.3.6.11_12942.20141204_BTCOEX20140507-4E40 not found
Error! Bad return status for module build on kernel: 5.11.0-25-generic (x86_64)
Consult /var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build/make.log for more information.
```

The make.log file is here:
[https://gist.github.com/kevin201/24b1387c6e289a7fa26c15a816b0fd8f](https://gist.github.com/kevin201/24b1387c6e289a7fa26c15a816b0fd8f)

Relevant lines appear to be:
```
/var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build/os_dep/osdep_service.c: In function ‘isFileReadable’:
/var/lib/dkms/rtl8723bu/4.3.6.11_12942.20141204_BTCOEX20140507-4E40/build/os_dep/osdep_service.c:728:11: error: implicit declaration of function ‘get_fs’; did you mean ‘get_sa’? [-Werror=implicit-function-declaration]
  728 |   oldfs = get_fs(); set_fs(KERNEL_DS);
      |           ^~~~~~
      |           get_sa
```

**Comment by lwfinger** [comment]
I do not do dkms. The only way that dkms gets into a repo is because someone else sent me the necessary patches.

I pushed the fixes for later kernels, but that particular release still does not build here. Please use the master branch.

**Comment by kevin201** [comment]
I thought I was using the master branch. It fails regardless of dmks.
